[package]
name = "jvm"
version = "0.1.0"
authors = ["Dom Williams <me@domwillia.ms>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cafebabe = {path = "../cafebabe"}
thiserror = "^1.0"
log = "^0.4"
env_logger = "^0.7"
itertools = "^0.9"
parking_lot = "^0.11"
strum = "^0.19"
strum_macros = "^0.19"
lazy_static = "^1.4"
